version: '3.8'
services:
  explore:
    build: ./exploreApp
    container_name: exploreApp
    ports:
      - "8080:8080"
    depends_on:
      - db-explore
      - statistic
    environment:
        DB_HOST: db-explore
        DB_PORT: 5432
        DB_NAME: explore_with_me
        POSTGRES_USER: kitty
        POSTGRES_PASSWORD: purrrrrr
        TZ: "Europe/Moscow"
        EXPLORE_STATISTIC: http://statistic:9090


  statistic:
    build: ./statisticApp
    container_name: statisticApp
    ports:
      - "9090:9090"
    depends_on:
      - db-explore
    environment:
      DB_HOST: db-explore
      DB_PORT: 5432
      DB_NAME: explore_with_me
      POSTGRES_USER: kitty
      POSTGRES_PASSWORD: purrrrrr
      TZ: "Europe/Moscow"

  db-explore:
    image: postgres:14.3-alpine
    container_name: db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: explore_with_me
      POSTGRES_USER: kitty
      POSTGRES_PASSWORD: purrrrrr
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres_db:/var/lib/postgresql/data